server:
  port: 8761

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: kgt-gateway
  cloud:
    gateway:
      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-append: false
        port-append: false
        proto-append: false
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        # Access registry server
        - id: registry
          uri: http://localhost:8762/
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        # Connect to Eureka
        - id: eureka
          uri: http://localhost:8762/eureka
          predicates:
            - Path=/eureka/**

        # Access authorization server
        - id: authorization
          uri: http://localhost:8081/
          predicates:
            - Path=/authorization/**
          filters:
            - StripPrefix=1


jwt:
  signing-key: bRJrESo3vfMfbuXr6IBA9QbT8gQs4PiY


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: kgt-gateway

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
